version: '3.6'
services:
  db:
    image: postgres:10.3
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${CANS_DB_PASSWORD}
