development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: cans
  pool: 5
  username: postgres
  password: example

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: cans_test
  pool: 5
  username: postgres
  password: example
